// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfFinance.Core.Data;

#nullable disable

namespace SelfFinance.Core.Migrations
{
    [DbContext(typeof(SelfFinanceAPIContext))]
    partial class SelfFinanceAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SelfFinanceAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<bool>("IsIncome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            IsIncome = true,
                            Name = "Salary"
                        },
                        new
                        {
                            CategoryId = 2,
                            IsIncome = false,
                            Name = "Food"
                        });
                });

            modelBuilder.Entity("SelfFinanceAPI.Models.FinancialOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10000.00m,
                            CategoryId = 1,
                            Date = new DateOnly(2024, 5, 1),
                            Description = "Salary",
                            IsIncome = true
                        },
                        new
                        {
                            Id = 2,
                            Amount = 250.50m,
                            CategoryId = 2,
                            Date = new DateOnly(2024, 5, 2),
                            Description = "Food",
                            IsIncome = false
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100.00m,
                            CategoryId = 2,
                            Date = new DateOnly(2024, 5, 3),
                            Description = "Food",
                            IsIncome = false
                        });
                });

            modelBuilder.Entity("SelfFinanceAPI.Models.FinancialOperation", b =>
                {
                    b.HasOne("SelfFinanceAPI.Models.Category", "Category")
                        .WithMany("Operations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SelfFinanceAPI.Models.Category", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
